import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import {
  Koh_Santepheap,
  Pacifico,
  Delius,
  Meow_Script,
  Libre_Bodoni,
  Noto_Serif_Display,
  WindSong,
} from "next/font/google";
import "./globals.css";
import Logo from "@/components/Logo";
import NavBar from "@/components/NavBar";

const notoSerifDisplay = Noto_Serif_Display({
  variable: "--font-noto-serif-display",
  subsets: ["latin"],
});

const libreBodoni = Libre_Bodoni({
  variable: "--font-libre-bodoni",
  subsets: ["latin"],
});

const windSong = WindSong({
  variable: "--font-windSong",
  subsets: ["latin"],
  weight: ["500", "400"],
});

const kohSantepheap = Koh_Santepheap({
  variable: "--font-koh-santepheap",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

const delius = Delius({
  variable: "--font-delius",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={`${notoSerifDisplay.variable} ${libreBodoni.variable} ${windSong.variable} ${kohSantepheap.variable} ${pacifico.variable} ${delius.variable}`}
        >
          <header className="flex justify-between items-center py-2 px-4 gap-4 h-16 min-w-screen bg-[#F3E5DA]">
            <div className="flex items-center gap-6 pt-1">
              <Logo />
              <NavBar />
            </div>
            <div className="flex items-center gap-4 text-[#8A3033]">
              <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
